package pojo;

// Generated Dec 20, 2013 9:23:39 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Account generated by hbm2java
 */
@Entity
@Table(name = "account", catalog = "appliances")
public class Account implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String username;
	private String password;
	private boolean isEnable;
	private String fullName;
	private String email;
	private String phone;
	private String address;
	private Boolean banned;
	private Set<Shoppingcart> shoppingcarts = new HashSet<Shoppingcart>(0);
	private Set<Userauth> userauths = new HashSet<Userauth>(0);

	public Account() {
	}

	public Account(String username, String password, boolean isEnable) {
		this.username = username;
		this.password = password;
		this.isEnable = isEnable;
	}

	public Account(String username, String password, boolean isEnable,
			String fullName, String email, String phone, String address,
			Boolean banned, Set<Shoppingcart> shoppingcarts, Set<Userauth> userauths) {
		this.username = username;
		this.password = password;
		this.isEnable = isEnable;
		this.fullName = fullName;
		this.email = email;
		this.phone = phone;
		this.address = address;
		this.banned = banned;
		this.shoppingcarts = shoppingcarts;
		this.userauths = userauths;
	}

	@Id
	@Column(name = "Username", unique = true, nullable = false, length = 31)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "Password", nullable = false, length = 51)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "IsEnable", nullable = false)
	public boolean isIsEnable() {
		return this.isEnable;
	}

	public void setIsEnable(boolean isEnable) {
		this.isEnable = isEnable;
	}

	@Column(name = "FullName", length = 50)
	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	@Column(name = "Email", length = 65535)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "Phone", length = 15)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "Address", length = 65535)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "Banned")
	public Boolean getBanned() {
		return this.banned;
	}

	public void setBanned(Boolean banned) {
		this.banned = banned;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	public Set<Shoppingcart> getShoppingcarts() {
		return this.shoppingcarts;
	}

	public void setShoppingcarts(Set<Shoppingcart> shoppingcarts) {
		this.shoppingcarts = shoppingcarts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	public Set<Userauth> getUserauths() {
		return this.userauths;
	}

	public void setUserauths(Set<Userauth> userauths) {
		this.userauths = userauths;
	}

}
