package pojo;

// Generated Dec 20, 2013 9:23:39 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Promotion generated by hbm2java
 */
@Entity
@Table(name = "promotion", catalog = "appliances")
public class Promotion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String promotionName;
	private Date dateStart;
	private Date dateEnd;
	private int valueSaleOff;
	private Boolean deleted;

	public Promotion() {
	}

	public Promotion(Date dateStart, Date dateEnd, int valueSaleOff) {
		this.dateStart = dateStart;
		this.dateEnd = dateEnd;
		this.valueSaleOff = valueSaleOff;
	}

	public Promotion(String promotionName, Date dateStart, Date dateEnd,
			int valueSaleOff, Boolean deleted) {
		this.promotionName = promotionName;
		this.dateStart = dateStart;
		this.dateEnd = dateEnd;
		this.valueSaleOff = valueSaleOff;
		this.deleted = deleted;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "PromotionName", length = 100)
	public String getPromotionName() {
		return this.promotionName;
	}

	public void setPromotionName(String promotionName) {
		this.promotionName = promotionName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DateStart", nullable = false, length = 10)
	public Date getDateStart() {
		return this.dateStart;
	}

	public void setDateStart(Date dateStart) {
		this.dateStart = dateStart;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DateEnd", nullable = false, length = 10)
	public Date getDateEnd() {
		return this.dateEnd;
	}

	public void setDateEnd(Date dateEnd) {
		this.dateEnd = dateEnd;
	}

	@Column(name = "ValueSaleOff", nullable = false)
	public int getValueSaleOff() {
		return this.valueSaleOff;
	}

	public void setValueSaleOff(int valueSaleOff) {
		this.valueSaleOff = valueSaleOff;
	}

	@Column(name = "Deleted")
	public Boolean getDeleted() {
		return this.deleted;
	}

	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}

}
