package pojo;

// Generated Dec 6, 2013 8:18:51 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Shoppingcart generated by hbm2java
 */
@Entity
@Table(name = "shoppingcart", catalog = "appliances")
public class Shoppingcart implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Account account;
	private Date orderDate;
	private Set<Shoppingcartdetail> shoppingcartdetails = new HashSet<Shoppingcartdetail>(0);

	public Shoppingcart() {
	}

	public Shoppingcart(Account account, Date orderDate) {
		this.account = account;
		this.orderDate = orderDate;
	}

	public Shoppingcart(Account account, Date orderDate, Set<Shoppingcartdetail> shoppingcartdetails) {
		this.account = account;
		this.orderDate = orderDate;
		this.shoppingcartdetails = shoppingcartdetails;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Username", nullable = false)
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "OrderDate", nullable = false, length = 10)
	public Date getOrderDate() {
		return this.orderDate;
	}

	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "shoppingcart")
	public Set<Shoppingcartdetail> getShoppingcartdetails() {
		return this.shoppingcartdetails;
	}

	public void setShoppingcartdetails(Set<Shoppingcartdetail> shoppingcartdetails) {
		this.shoppingcartdetails = shoppingcartdetails;
	}

}
