package pojo;

// Generated Dec 6, 2013 8:18:51 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Userauth generated by hbm2java
 */
@Entity
@Table(name = "userauth", catalog = "appliances")
public class Userauth implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private UserauthId id;
	private Account account;

	public Userauth() {
	}

	public Userauth(UserauthId id, Account account) {
		this.id = id;
		this.account = account;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "username", column = @Column(name = "Username", nullable = false, length = 31)),
			@AttributeOverride(name = "authority", column = @Column(name = "Authority", nullable = false, length = 15)) })
	public UserauthId getId() {
		return this.id;
	}

	public void setId(UserauthId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Username", nullable = false, insertable = false, updatable = false)
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

}
